import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

export const REPO_ROOT = path.resolve(fileURLToPath(import.meta.url), '../../..');
export const MODULES_DIR = path.join(REPO_ROOT, 'modules');

export const REPO_SLUG = 'Zeralius/Zeras-vtt-forge-tools';
export const DEFAULT_BRANCH = 'main';

// The bundle module doesn't do anything itself, it just depends on all the others so people can
// install everything at once. It's generated by scripts/bundle.mjs, don't edit it by hand.
export const BUNDLE_ID = 'zeras-forge-tools';

// This is the URL Foundry pings to find out whether there's a newer version, so it has to keep
// working forever. Pointing at the branch instead of a release means it never goes stale.
export function manifestUrl(id) {
    return `https://raw.githubusercontent.com/${REPO_SLUG}/${DEFAULT_BRANCH}/modules/${id}/module.json`;
}

// Points at one exact version's zip, so an old release keeps handing out the files it shipped with.
export function downloadUrl(id, version) {
    return `https://github.com/${REPO_SLUG}/releases/download/${releaseTag(id, version)}/${id}.zip`;
}

export function projectUrl() {
    return `https://github.com/${REPO_SLUG}`;
}

// Tags look like `hp-in-bar-v1.0.7`. Ids can contain dashes, versions can't, so splitting on the
// last `-v` is unambiguous.
export function releaseTag(id, version) {
    return `${id}-v${version}`;
}

// Returns null for tags that aren't module releases, e.g. the old `module_release` tag.
export function parseReleaseTag(tag) {
    const match = /^(?<id>.+)-v(?<version>\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?)$/.exec(tag);
    return match ? { id: match.groups.id, version: match.groups.version } : null;
}

// Every module in the repo, bundle included. Pass { includeBundle: false } when you want only the
// real ones, e.g. when building the bundle's dependency list.
export function listModuleIds({ includeBundle = true } = {}) {
    if (!fs.existsSync(MODULES_DIR)) return [];
    return fs.readdirSync(MODULES_DIR, { withFileTypes: true })
        .filter(entry => entry.isDirectory() && fs.existsSync(path.join(MODULES_DIR, entry.name, 'module.json')))
        .map(entry => entry.name)
        .filter(id => includeBundle || id !== BUNDLE_ID)
        .sort();
}

export function moduleDir(id) {
    return path.join(MODULES_DIR, id);
}

export function manifestPath(id) {
    return path.join(moduleDir(id), 'module.json');
}

export function readManifest(id) {
    return JSON.parse(fs.readFileSync(manifestPath(id), 'utf8'));
}

// Always writes with the same indentation and a trailing newline, so releases don't produce
// pointless whitespace diffs.
export function writeManifest(id, manifest) {
    fs.writeFileSync(manifestPath(id), `${JSON.stringify(manifest, null, 2)}\n`, 'utf8');
}

export function isSemver(version) {
    return /^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/.test(version);
}

export function bumpVersion(version, kind) {
    const [major, minor, patch] = version.split('-')[0].split('.').map(Number);
    if (kind === 'major') return `${major + 1}.0.0`;
    if (kind === 'minor') return `${major}.${minor + 1}.0`;
    if (kind === 'patch') return `${major}.${minor}.${patch + 1}`;
    throw new Error(`Unknown bump kind: ${kind}`);
}
